
# Data 
dataset_dir: "cv/ml/data/dataset"   
patch_size: 70                      
val_split: 0.2                       # 20% of data used as validation set


dropout: 0.5                         

# Training 
epochs: 50                           # long training for best performance
batch_size: 32                       
learning_rate: 0.0003               
weight_decay: 0.00001                

#  Early stopping 
patience: 15                         

# Scheduler 
lr_scheduler_factor: 0.3
lr_scheduler_step_size: 15


#- Saving 
weights_out: "cv/ml/weights/square_classifier.pth"  
save_best_only: true          # keep only best model (based on val_loss)

#  Logs 
log_interval: 10              # fewer logs for long training runs